version: '3.8'
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: <admin-user>
      MINIO_ROOT_PASSWORD: <admin-pass>
      MINIO_BROWSER_REDIRECT_URL: http://minio:9001
      MINIO_SERVER_URL: http://minio:9000
      MINIO_DOMAIN: minio
    volumes:
      - ./minio-data:/data
    command: server --console-address ":9001" /data
    restart: unless-stopped
    networks:
      - labelstudio-network

networks:
  labelstudio-network:
    external: true
